### ISSUE TITLE
cornerstone_tools__WEBPACK_IMPORTED_MODULE_10__["mouseInput"].enable error on simple react installation

### ISSUE THREAD

**Issue by pzehle** [cornerstonejs/cornerstoneTools#822] opened 2019-02-08 20:46 UTC
### Prerequisites

* [ X] Are you running the latest version?
* [ X] Are you reporting to the correct repository?
* [ X] Did you perform a cursory search?

For more information, see the `CONTRIBUTING` guide.

### Description

I've been using cornerstonejs for quite some time now. I am currently trying to adapt my tool to use cornerstone tools. The problem is that I get this error and don't know how to fix it nor how it's been generated.

Unhandled Rejection (TypeError): undefined is not an object (evaluating 'cornerstone_tools__WEBPACK_IMPORTED_MODULE_10__["mouseInput"].enable')

### Steps to Reproduce

1. After trying to simply install it on my current tool and nothing seems to work, I've search for some people that have done the same. You can check [this url](https://codesandbox.io/s/rm1y2l1xz4). I tried to adapt my tool to his code, nothing. Then I literally copied his code and put it in my project, same error.

**Expected behavior:** Tool to work as the link provided.

**Actual behavior:** Getting this error no matter if it is an adaptation to my tool or the exact same code as this person.

### Codepen With Reproduction of Issue:

- [Basic Template](https://codesandbox.io/s/x2po962wlq)

![screenshot 2019-02-08 at 21 46 23](https://user-images.githubusercontent.com/27866874/52505180-02745c80-2beb-11e9-8cc0-0de59d5d9bff.png)

**Comment by dannyrb** [comment] 2019-02-08 21:18
Hello @pzehle, your codepen doesn't include any external dependencies. It looks like you've copy and pasted your code, but not actually imported any libraries.

A simple demo may be easier to build with CodeSandbox, as it supports static resources (like the webworker tasks). While less than ideal, you can see a simple setup using Vue + V3 of our `cornerstone-tools` in [this CodeSandbox template](https://codesandbox.io/s/1qj7j8op0l). The only code that matters is sitting in `/components/HelloWorld.vue`

I'm not 100% sure what's causing your issue without a minimal reproduction. It's worth noting that you _may be_ trying to use `Version 3` of `cornerstone-tools` with `Version 2`'s syntax.

**Comment by pzehle** [comment] 2019-02-08 21:35
Hello @dannyrb , you are right, sorry for that.

I am sending the full template [here](https://codesandbox.io/s/x2po962wlq). All dependencies are there and that is the code that should be working. Thanks again.

**Comment by dannyrb** [comment] 2019-02-08 21:49
@pzehle, we're getting closer (:

The `cornerstone-core` version you're using is 2 major versions behind. The `cornerstone-tools` version you're using is `3.x`, but the syntax you're using if for `cornerstone-tools@2.x`

**Comment by pzehle** [comment] 2019-02-08 23:19
@dannyrb thanks! :)

I am sorry for this question, but on npm's site, the latest versions are:

cornerstone-core: 2.2.8
cornerstone-tools: 3.0.2

Which are the ones that I am using.

Also, I've been searching for hours for examples on how to do this, and only the 2.x syntax comes to me. Would you be so kind to share examples with syntax from version 3?

Thanks again!

**Comment by pzehle** [comment] 2019-02-09 00:12
Also, I am moving to the syntax of version 3. Even calling `const csTools = cornerstoneTools.init();` returns undefined. Seems to me that I am on a dead end and cannot seem to find examples or further details on usage. I don't know if I should move back to version 2 or if you could help.

Thanks!

**Comment by dannyrb** [comment] 2019-02-09 18:11
@pzehle, version 3 has been out less than a week. There are some docs at:

https://tools.cornerstonejs.org

I'll whip up a minimal example that uses cornerstoneWadoImageLoader and share it here. If you encounter any pain points with the docs, specific targeted feedback will help us determine which parts need priority attention -- also, feel free to PR doc changes ^_^

**Comment by pzehle** [comment] 2019-02-09 18:58
@dannyrb thanks, I would really appreciate the minimal example. Personally, I have problems to start using a framework if no minimal examples are available, and in this case, even starting the framework returns undefined. The docs are OK, but I really have no idea how to start the framework. Once I have the minimal example, I can now continue with the docs and debug myself. So, thanks for the support again and I look forward for the example.

**Comment by dannyrb** [comment] 2019-02-10 04:33
## Live Example:

- Sandbox, using your `.dcm` file: https://codesandbox.io/s/9z04x8ykjr

## Notes

### Input Listeners

_Version 2_
```js
cornerstoneTools.mouseInput.enable(element);
cornerstoneTools.mouseWheelInput.enable(element);
cornerstoneTools.touchInput.enable(element);
```

_Version 3_
```js
cornerstoneTools.init({ /* options */ });
```
In version 3, we listen for these by default for each `enabledElement` you create after calling `cornerstoneTools.init({ /*option*/ })`

### Activating Tools

_Version 2_
```js
cornerstoneTools.wwwc.activate(element, 1);
cornerstoneTools.pan.activate(element, 2);
cornerstoneTools.zoom.activate(element, 4);
cornerstoneTools.zoomWheel.activate(element);
cornerstoneTools.panTouchDrag.activate(element);
cornerstoneTools.zoomTouchPinch.activate(element);
```

In Version 2, we can `activate` a built-in tool for a given `enabledElement`. The 2nd option, when activating a `mouseButtonTool` is the `mouseButtonMask` used to determine which button(s) the tool should respond to.

_Version 3_
```js
// Grab Tool Classes
const WwwcTool = cornerstoneTools.WwwcTool;
const PanTool = cornerstoneTools.PanTool;
const PanMultiTouchTool = cornerstoneTools.PanMultiTouchTool;
const ZoomTool = cornerstoneTools.ZoomTool;
const ZoomTouchPinchTool = cornerstoneTools.ZoomTouchPinchTool;
const ZoomMouseWheelTool = cornerstoneTools.ZoomMouseWheelTool;

// Add them
cornerstoneTools.addTool(PanTool);
cornerstoneTools.addTool(ZoomTool);
cornerstoneTools.addTool(WwwcTool);
cornerstoneTools.addTool(PanMultiTouchTool);
cornerstoneTools.addTool(ZoomTouchPinchTool);
cornerstoneTools.addTool(ZoomMouseWheelTool);

// Set tool modes
cornerstoneTools.setToolActive("Pan", { mouseButtonMask: 4 }); // Middle
cornerstoneTools.setToolActive("Zoom", { mouseButtonMask: 2 }); // Right
cornerstoneTools.setToolActive("Wwwc", { mouseButtonMask: 1 }); // Left & Touch
cornerstoneTools.setToolActive("PanMultiTouch", {});
cornerstoneTools.setToolActive("ZoomMouseWheel", {});
cornerstoneTools.setToolActive("ZoomTouchPinch", {});
```

In Version 3, we make this a 2-step process. You need to:

1. Add a tool
    - `cornerstoneTools.addTool(ToolClass)` OR
    - `cornerstoneTools.addToolForElement(enabledElement, ToolClass)`
2. Set the tool's mode
    - `cornerstoneTools.setToolActive("ToolName", { /* options */ })` OR
    - `cornerstoneTools.setToolActiveForElement(enabledElement, "ToolName", { /* options */ })`

Where `addTool` and `setToolActive` apply to all currently enabled elements, and their `ForElement` counterparts allow for finer control.

## Parting Thoughts

I realize Version 3 may feel a bit more verbose, but it helps solve some common problems that surface pretty quickly when using Version 2. If you want specific examples of _why_ we made the changes, I can delve deeper.

Or if you have additional questions about version 3's usage, I can whip up some examples there as well.

> Also, I am moving to the syntax of version 3. Even calling `const csTools = cornerstoneTools.init();` returns undefined.

The `Version 3` docs I linked you to were written before the API had been finalized. Unfortunately, this means parts of it are outdated and misleading. If you can point me toward the page(s) and excerpts that _don't work_, I'll try to update them. If you're feeling brave, please feel free to submit a pull request with any changes you feel may correct outdated or incorrect documentation (all of our docs are simple `markdown` documents).

**Comment by dannyrb** [comment] 2019-02-10 04:41
I think I've answered the heart of your question. I'm going to close this issue, but we can continue to discuss here. If there are _actionable_ items that should result in specific updates to the documentation or changes to the library, we can create a new issue.

**Closed by dannyrb** 2019-02-10 04:41 UTC
Labels: ❓ Question, 📖 Documentation, 📦 Version 3

**Comment by pzehle** [comment] 2019-02-10 11:10
@dannyrb I really need to thank you, not everyone helps with this kind of issues to people like me haha. Many thanks. Now it is working, I am not really sure where was the problem, but now I can use / debug the tools myself, also, I kind of understand the API now that I can initialize the framework.

Just two small questions, and let me know if you can help.

1. I have a set of dicom images and I want to scroll them with the tools. I see in the API there is a `cornerstoneTools.StackScrollMouseWheelTool;`. I activate it and of course it does nothing because no stack is defined. Could you please specify how to tell the tool which images to use for scrolling?
2. This must be an easy one and maybe has nothing to do with the framework, but for example, I want to use X tool for the mouse button 2, which is the right button. The tool doesn't recognize this button as the browser does its default stuff. Is there any additional configuration to the tool that allows me to use the right click? Or maybe this has to be done anywhere else?

I can just thank you again for your support.

**Comment by pzehle** [comment] 2019-02-10 13:35
@dannyrb I really need to thank you, not everyone helps with this kind of issues to people like me haha. Many thanks. Now it is working, I am not really sure where was the problem, but now I can use / debug the tools myself, also, I kind of understand the API now that I can initialize the framework.

I have a problem now, and I don't know if we should discuss this here, or maybe somewhere else.

As said before, everything is worked as expected now. My bigger issue here is with frames. When I try to access a file's frames, I get an error of "no frames meta data found". If I `console.log()` the data from the dicom file I gave you, in fact no 'x00280008' data is found, so this would mean my file has no multiframes. If I open this set in a dicom viewer application (like Horos on macOs) and I scroll over the images, actually they have frames, because the view is way smoother than in my application. I will put here two videos so you can see what I mean and maybe point me in the right direction or point where should I discuss this:

Horos:
![ezgif-3-89895e15c935](https://user-images.githubusercontent.com/27866874/52534343-c6eba680-2d40-11e9-9a88-5284f80046ce.gif)

My app:
![ezgif-3-dd567858e40c](https://user-images.githubusercontent.com/27866874/52534360-f13d6400-2d40-11e9-9268-9067b23edb45.gif)

As you can see in the videos, the Horos app seems to read the frames OK (even though there is no frame meta data). And in my application, it shows like skipping, so it is missing frames. Any thoughts on this?

Thanks!

**Comment by pzehle** [comment] 2019-02-10 17:53
Hello again @dannyrb, regarding your comment for me to point you where the docs are not being completely clear:

On [https://tools.cornerstonejs.org/api/#addToolState](this api section) (addToolState), it states that you have to provide the enabled element, the name of the tool and as well the previously saved state of the mentioned tool. If my login is right, when I save in database or localStorage for example the points I created with a `ProbeTool`, the data saved doesn't contain information about the current slice on the stack. This means, when I try to `addToolState` with the required information, I get a TypeError saying it cannot convert undefined or null to object, not very specific, but I think it is trying to tell that I am not providing a current image ID, this is if I am not mistaken.

Would be good to add to the API how and where to indicate the slice ID so the tool knows in which slice it is going to add the previously saved state.

Thanks! And of course, correct me if I am wrong, I've been using your framework for 2 days now, I am no expert.

**Comment by dannyrb** [comment] 2019-02-10 18:23
> As you can see in the videos, the Horos app seems to read the frames OK (even though there is no frame meta data). And in my application, it shows like skipping, so it is missing frames. Any thoughts on this?

It's difficult to know what's happening without a minimal reproduction. This looks like a CT, so I'm guessing this is many DICOM files that you scroll through using StackScroll. My best guess is that HOROS automatically places these files in the correct order, and that in your web application the files are unsorted/out of order.

It's _likely_ not a multiframe image, but rather a series of images. I wouldn't know for certain without a reproduction.

> Would be good to add to the API how and where to indicate the slice ID so the tool knows in which slice it is going to add the previously saved state

This is a good note! Thank you. We need much better docs on saving/restoring tool state. It's a very common use case.

**Comment by pzehle** [comment] 2019-02-10 20:17
Hi @dannyrb, thanks for your answer.

After hours of debugging, I see that in fact, it is no multi-frame (thanks for pointing that out), it is just a set of individual images.

As of right now, I get the images from a server, then load it and cache them into cornerstone, and then when I see the "slice location" of each image, in fact, they are not ordered. This is weird, because the sets I am getting from the University are named like 000000.dcm, 000001.dcm and so on, but these names don't point out order. I literally have no idea how to order the array, as before loading it into cornerstone I have no access to the file's metadata, and after loading it I don't seem to be able to change the stack or even the order of the already loaded url's. Is there any cornerstone method to order the files by slice location? The code is 'x00201041' for the location inside the set. Or maybe any thoughts on this? I am going to change the code sandbox with what I have now and then maybe you can help me with this. Thanks!

**Comment by pzehle** [comment] 2019-02-10 20:48
@dannyrb, the updated sandbox is [here](https://codesandbox.io/s/x2po962wlq). Thanks again for the support.

**Comment by swederik** [comment] 2019-02-10 21:32
If you don't have the metadata ahead of time, what you can do is use cornerstone.loadAndCacheImage to retrieve your images first, then check the imagePlaneMetadata via cornerstone.metadata.get('imagePlaneMetadata', imageId), and sort them by imagePositionPatient, and then create the stack.

**Comment by pzehle** [comment] 2019-02-10 23:13
Hello @swederik, thanks for the support. Should I get the metadata once the image is loaded? I mean, if I call the function inside the `loadAndCacheImage` promise, I get the following error:

`Unhandled Rejection (TypeError): Cannot read property 'get' of undefined`

Anyway, the problem is, I was trying to get the order of the images based on the location code `('x00201041')`. I can in fact retrieve the data, the problem comes when I have to order the array, because when I retrieve this data inside `loadAndCacheImage`, which to my understanding is asynchronous, the other part of the code crashes, as there are no images _(yet)_ to be loaded into the canvas.

**Comment by dannyrb** [comment] 2019-02-10 23:46
@pzehle, we may be drifting away from library questions and more toward programming or medical imaging questions.

There's nothing wrong with that, but please realize we're less apt to prioritize non-library questions. You may have more luck on StackOverflow, our Google Group, or with other communities.

Back to your question. Ideally, you know the order before sending down the images. For large series, waiting for all images before ordering and displaying an image can be prohibitive. If you _must_ check on the client, `loadAndCacheImage` returns a promise. You can `Promise.all` them, or update the load progress of the series by updating a counter in each promise's `then` -- when the counter is equal to the number of known images in the series, the entire series will likely have been loaded.

**Comment by pzehle** [comment] 2019-02-10 23:49
@dannyrb yes, I know we are misleading this. Nevertheless, I think this solution may be helpful for someone with the same situation. I know how to order arrays of any dimensions, the problem comes when this sorting has to be done inside a promise, because this promise gets the information I need to complete this sorting. I will work with this by myself and let you know of the outcome. Anyway, you've been more than helpful.

Thanks!

**Comment by pzehle** [comment] 2019-02-11 00:14
@dannyrb and @swederik million thanks for the help. I've finally made it with async/await. I have the updated sandbox [here](https://codesandbox.io/s/x2po962wlq).

Thanks again and I hope if someone is in the same situation, finds a solution here.

**Comment by pzehle** [comment] 2019-02-11 19:46
Hey @dannyrb and @swederik, sorry for bothering again.

Could you please help, if possible, to point me in the right direction to change the annotation color? Couldn't find anywhere in the docs about this setting. Currently the probe annotations shows white, and on hover green. I want them to be red or some other color all the time. Is this possible? Thanks!

**Comment by dannyrb** [comment] 2019-02-11 20:10
https://github.com/cornerstonejs/cornerstoneTools/blob/0aae680b20c3777866a49354465f5c2b78f7ffc6/src/stateManagement/toolColors.js

`cornerstoneTools.toolColors.setActiveColor(/* color */)`
