### ISSUE TITLE
Clear tool state of brush not work

### ISSUE THREAD

**Issue by drozdzynski** [cornerstonejs/cornerstoneTools#626] opened 2018-10-08 07:16 UTC
### Prerequisites

* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you perform a cursory search?

### Description

When I try clear tool state of `brush` with function:
```cornerstoneTools.clearToolState(cornerstoneElement, "brush")```
I have error:
```
Uncaught TypeError: Cannot read property 'pixelData' of undefined
    at HTMLDivElement.x (brushTool.js:163)
    at triggerEvent (triggerEvent.js:23)
    at ./internal/drawImageSync.js.__webpack_exports__.default (drawImageSync.js:78)
    at draw (enable.js:98)
```

### Steps to Reproduce

1. Activate brush
2. Clear brush tool state
3. Update image

**Expected behavior:** 
Should clear `brush` tool state.

**Actual behavior:** 
Clear not work and crash application.

### Codepen With Reproduction of Issue:

- https://codepen.io/anon/pen/YJpxjq

**Comment by swederik** [comment] 2018-10-08 09:08
Thanks for the codepen to reproduce the issue! It looks like it's here: https://github.com/cornerstonejs/cornerstoneTools/blob/master/src/paintingTools/brush.js#L32

**Comment by JamesAPetts** [comment] 2018-10-08 09:10
Hey @drozdzynski , thanks for the report! The brush tool in v2 has a lot of issues, and was largely experimental, as the framework for such segmentations wasn't up to scratch.

Proper support for segmentation tools are one of the big drivers of an upcoming major release, where 90+% of our development effort is currently focused. I think this issue is already fixed in the `vNext` branch. I'll keep note of this issue and will make sure it doesn't propagate to v3.

**Comment by JamesAPetts** [comment] 2018-10-08 09:15
That being said, its a fix for v2 probably isn't too difficult, feel free to try catching the exception and exit the rendering, I'd be happy to review a PR.Since we have a major update coming in the near future, it doesn't have to be super pretty.

You can probably just create `toolData.data[0].pixelData` again as a blank `Uint8ClampedArray`if it doesn't exist.

**Comment by dannyrb** [comment] 2019-02-05 19:42
I'm going to close this issue. If some brave soul wants to spearhead a PR for `Version 2`, feel free to comment/re-open. We will be providing very limited support for V2 requests, so it may be in your best interest to migrate to Version 3

**Closed by dannyrb** 2019-02-05 19:42 UTC
Labels: 🐛 Bug: Verified, 📦 Version 2, 🙋 Up For Grabs

**Comment by FMCalisto** [comment] 2023-03-14 21:10
In one of my [StackOverflow answers](https://stackoverflow.com/a/73204850/2371987), I explain how to use the `clearToolState` function to remove all states from the state manager corresponding to the name and element of a tool. This function can be used to clear the state of the brush tool in CornerstoneJS, which is causing an error provided in [this issue](https://github.com/cornerstonejs/cornerstoneTools/issues/1440#issuecomment-1468743931). There are [several examples and issues](https://github.com/search?q=org%3Acornerstonejs+clearToolState&type=issues) related to this problem that can be followed, and that it is important to understand how CornerstoneTools store their values.
