### ISSUE TITLE
Bug when activating stackScroll before stackScrollTouchDrag at the same time.

### ISSUE THREAD

**Issue by medihack** [cornerstonejs/cornerstoneTools#338] opened 2018-01-30 22:42 UTC
When activating `stackScrollTouchDrag` after(!) `stackScroll` then `stackScroll` (using the mouse) is not working anymore (only the touch one is working). When activating them the other way around (`stackScrollTouchDrag` before `stackScroll`) both work fine. I didn't get that error with other tools yet (e.g. `wwwc`). Not a critical bug, but an annoying one ;-)

**Comment by dannyrb** [comment] 2018-01-31 01:15
Thanks for reporting this. I'll see if I can duplicate it in a codepen and post the example here. I'll mark this as a `verified bug` after I can reproduce it.

**Comment by medihack** [comment] 2018-02-03 11:52
Is there a preconfigured Codepen template for testing such things?

**Comment by medihack** [comment] 2018-02-03 13:16
I created a Codepen that shows the issue: https://codepen.io/medihack/pen/mXVYdX
If you simply swap lines 23 and 24 then both work fine again (tested on a Microsoft Surface Pro).

**Comment by amitpanwar123** [comment] 2018-02-17 12:17
I am unable to scroll XA images in cornerstone. Used URL like : Dicom//201712221750420360/Standered/1.2.840.114257.1.16356791.20175100.dcm?frame=2

**Comment by vaibhav2383** [comment] 2018-02-20 08:33
I have created a pull request that fixes this issue. https://github.com/cornerstonejs/cornerstoneTools/pull/352

**Comment by swederik** [comment] 2018-05-28 08:40
Closing because I believe @vaibhav2383 fixed this.

**Closed** 2018-05-28 08:40 UTC
Labels: verified bug
