### ISSUE TITLE
is this lib support  display the overlayData(60003000) of dicom

### ISSUE THREAD

**Issue by sumilying** [cornerstonejs/cornerstoneTools#751] opened 2018-12-12 02:03 UTC
### Description

 
 Some dicom file have imageData(0x7fe00010) and overlayData(0x60003000);corner tools draw imageData default,but the overlayData is ignore default. Is there other display method to show both the imageData and overlayData at the same time.

**Comment by sumilying** [comment] 2018-12-13 07:50
Some dicom file  have imageData(0x7fe00010) and overlayData(0x60003000);corner tools draw imageData default,but the overlayData is ignore default. Is there other   display method to show both the imageData and overlayData at the same   @time.

**Comment by kofifus** [comment] 2019-01-21 21:52
duplicate of https://github.com/cornerstonejs/cornerstone/issues/277

**Comment by dannyrb** [comment] 2019-01-25 14:00
Thanks, @kofifus!
@sumilying feel free to add clarification or additional information if you don't believe this issue is a duplicate; otherwise, please continue discussion in the thread @kofifus linked to.

**Closed by dannyrb** 2019-01-25 14:00 UTC
Labels: duplicate
