### ISSUE TITLE
Hide a tool's rendered cached stats or text

### ISSUE THREAD

**Issue by pzehle** [cornerstonejs/cornerstoneTools#985] opened 2019-06-25 20:58 UTC
### Prerequisites

* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you perform a cursory search?

### Description

I am currently developing an algorithm that creates a lot of Probe elements inside a RectangleRoi depending on the HU. This is to create segments of areas that are not air. Basically, automatically paint tumours or other parts of the body.

However, this Probe has of course the MO and SP data shown with the circle. I would like to know if it is possible to only show the circle without any cached stats text attached to it, because this algorithm is pixel by pixel so the stats are overlapped with each other (see pictures).

![Screenshot 2019-06-25 at 22 55 56](https://user-images.githubusercontent.com/27866874/60132822-90b53d80-979c-11e9-8999-423e7d8caa2e.png)
![Screenshot 2019-06-25 at 22 57 50](https://user-images.githubusercontent.com/27866874/60132888-afb3cf80-979c-11e9-99c8-33ef0398a005.png)

**Comment by dannyrb** [comment] 2019-06-26 02:19
> This is to create segments of areas that are not air. Basically, automatically paint tumours or other parts of the body.

While this is certainly something we can add support for (and it may already exist, I'd have to double check), why not "paint" using the brush tool instead? It is a much more common representations for segments.

**Comment by pzehle** [comment] 2019-06-26 22:16
Hi @dannyrb, as usual, thanks for your quick response.

My first choice was to use the Brush Tool. While the first thing I did was to check up what information it brings from getToolState, there is an error, you have to use 'brush' instead of 'Brush', and this is not stated, so I got confused. Next, I painted on my canvas and checked the tool state, it brings hundreds of thousands of arrays with value 0, so I don't really now what this represents. Next, for some reason, after activating the BrushTool, it makes the whole canvas in a state that it is constantly updating, for example, I have a renderTime function from state, that `onImageRender()` gets the time it took to render that image, and as `onImageRender()` is called once an image is rendered, this render time is somewhat static. When using the BrushTool, this render time is constantly being updated, like `onImageRender()` is being called every frame, I don't really know what is causing this, I just know is the BrushTool as this only happens with this tool. And finally, I don't know how to specify the brush tool an X and Y coordinate to paint to. This is something I can do with the other tools, but as I don't really understand the BrushTool structure, I don't know how to specify this information. So this is why I went with the ProbeTool instead of the BrushTool. If this points are something you can help me with, would be great, if not, then I would really be interested in an option for hiding/showing a tool's text.

Thanks again!

**Comment by dannyrb** [comment] 2019-06-27 04:05
Brush is a bit of an odd beast. You're also correct that it's not documented well. The current version feels more like a work-in-progress prototype, and it's actually getting a decent overhaul in the coming months. That being said, it's likely a better candidate for what you're trying to accomplish. Both in it's current form, and it's upcoming one.

> there is an error, you have to use 'brush' instead of 'Brush'

Good catch. I'll need to double check with @JamesAPetts that this is fixed in the rewrite.

> tool state, it brings hundreds of thousands of arrays with value 0, so I don't really now what this represents.

The brush tool's data is really just an array of "pixels", where `0` indicates that there is no brush data at that position. This is similar-ish to how we render the pixelData for each image.

>  after activating the BrushTool, it makes the whole canvas in a state that it is constantly updating

This is caused by the brush tool's "cursor". You'll notice the red circle that travels with your mouse as it moved. When a tool with cursors is enabled, or if cursors are enabled globally, the canvas must re-render on `mouseMove` to show the updated cursor.

This is the advantage of native or SVG cursors, as they don't require us to force a re-render.

> I don't know how to specify the brush tool an X and Y coordinate to paint to

The brush data is a 1D array of pixels. If your reference image is `512`x`512`,  index `0` would map to the top left pixel of your image, and `262,144` (512 rows * 512 cols - 1 offset for 0-index) would map to the bottom right pixel of your image. You can find the position of the corresponding pixel in the array using x (your column) and y (your row).

It's a bit late for me and I'm saying the bulk of this from memory, so it may not all be 100% accurate, but it should be close. If you need me to expand on anything, please don't hesitate to reach out.

**Comment by pzehle** [comment] 2019-06-27 08:30
Hey @dannyrb, thanks again for your response.

This helps me a lot, I think now I understand how this tool works. It is very clear and I thank you for the detailed explanation. I have just two more question to finish this thought:

1. In case I use the BrushTool. How could I deactivate the cursor so I don't have this re-render stuff on mouse move? For me this is very important as the application I am building has a lot of processes and stuff that already makes it heavy, and this re-render makes it work slow and this completely destroys the UX I'm trying to keep. Is this something I can do?
2. In case I decided to keep the ProbeTool, did you have the chance to check if there is already an option to hide the text? Maybe for this particular case I'd stick with the BrushTool, but this hidden text would make other processes I have in mind a lot easier for the eye without this text.

Thanks again! :)

**Comment by dannyrb** [comment] 2019-06-27 13:22
> How could I deactivate the cursor?

I don't know that you can. We need some way to show you the size and placement of the brush for when you interact with the canvas. We've looked at SVG cursors, but providing an SVG to the browser hits a dimension limitation that we often need to surpass. We could add an "SVG layer" for rendering things like this that don't trigger canvas re-renders, but that would be far-future.

If you have other logic that fires on re-render, you may want to look into `throttle`, which is notably different from `debounce`, or finding a different hook/event to leverage.

>  is already an option to hide the text?

Here is where the [probe tool renders its text boxes](https://github.com/cornerstonejs/cornerstoneTools/blob/master/src/tools/annotation/ProbeTool.js#L200-L207). You could update the render method to use a new property on the tool's options to conditionally render them. This would require a PR, but is one I would review.

**Comment by pzehle** [comment] 2019-06-27 13:54
Thanks for the information and the help. I will definitely work on a PR for this and then let you know.

**Closed** 2019-07-22 13:01 UTC
Labels: Question :question:, 😎 Historically Cool

**Comment by erasromani** [comment] 2022-03-28 13:56
Has anyone been able to hide annotation tool's cached stats and text like Area, Mean, and Std Dev?
