### ISSUE TITLE
BrushTool triggers non-stop 'cornerstoneimagerendered' events

### ISSUE THREAD

**Issue by luckfamousa** [cornerstonejs/cornerstoneTools#377] opened 2018-03-26 16:46 UTC
As soon as I activate the brush tool cornerstone fires 'cornerstoneimagerendered' non-stop without any user interaction.
Can you immediately reproduce that or do you need a code example?

Cheers, Felix

I am using the latest cornerstone/cornerstoneTool versions from NPM. 
Chrome Version 65.0.3325.181 (Mac).

**Comment by swederik** [comment] 2018-03-27 12:15
Hi Felix,

It might be due to this line:

https://github.com/cornerstonejs/cornerstoneTools/blob/master/src/paintingTools/brushTool.js#L72

I don't really see any reason to keep it, but I haven't dug into it yet. Try commenting that line out and checking if anything else breaks. I would note that cornerstoneimagerendered fires on the hover movement as well, which is probably not optimal. Maybe we should change that.

**Comment by swederik** [comment] 2018-05-11 10:35
@pieper and I have been working on changing the brush tool to prevent this / other issues. I'll try to post here when we have some updates.

**Comment by dannyrb** [comment] 2018-08-18 15:30
@JamesAPetts or @swederik, does this problem persist in the `vNext` branch? Should we add this to the project board if it is not yet resolved?

If this has been addressed, I would like to close out the issue and note it will be fixed in `v3`

**Comment by JamesAPetts** [comment] 2018-08-19 00:16
@dannyrb, I haven't checked if this has been resolved, can check on Monday, so leave open for now.

**Comment by dannyrb** [comment] 2018-09-22 10:32
@JamesAPetts, do we have a status on this?

**Comment by JamesAPetts** [comment] 2018-09-23 21:51
Hey @dannyrb , this currently doesn't happen on vNext because of a caching mechanism I've put in. You still get render events when we re-render the cursor on mouse move, but this will be non-existant once we have SVG cursors.

**Comment by dannyrb** [comment] 2019-02-05 19:01
If we don't see any activity on this issue for another few months, I will likely close it. If you can reproduce this issue in the latest version (Version 3), please open a new issue with your findings and reproduction.

**Closed** 2019-07-22 13:07 UTC
Labels: :three: Priority: Low, Bug: Verified :bug:, Up For Grabs :raising_hand_woman:, Version 2 :package:
